import { TolgeeNextProvider } from '@/app/TolgeeNextProvider';
import type { Metadata } from 'next';
import { useLocale } from 'next-intl';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

export default async function RootLayout({ children }: Props) {
  const locale = useLocale();
  const locales = {
    en: await import(`../../../public/i18n/en.json`).then((m) => m.default),
    [locale]: await import(`../../../public/i18n/${locale}.json`).then(
      (m) => m.default
    ),
  };

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <TolgeeNextProvider locales={locales} locale={locale}>
          {children}
        </TolgeeNextProvider>
      </body>
    </html>
  );
}
